"use client";
import { Inter, Raleway } from "next/font/google";

import "~/assets/css/bootstrap.min.css";
import "~/assets/css/app.css";
import "~/assets/css/main.css";
import "~/assets/css/react-adjustment.css";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  display: "swap",
});

export const metadata = {
  title: "AvatoAI",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/favicon.ico?v=4"],
    shortcut: ["/favicon.ico"],
  },
};

import ErrosSection from "~/components/Section/Erros/ErrosSection";

const NotFoundPage = () => {
  return (
    <>
      <ErrosSection />
    </>
  );
};

export default NotFoundPage;
